import { executeChatCompletion } from '../ai-provider/client';
import { PlanningError } from './errors';
import { ChangeSetDto } from './schemas';
import { getAiModel } from '../ai-model-resolver';

export interface ReviewResult {
  approved: boolean;
  riskLevel: 'low' | 'medium' | 'high';
  feedback: string;
  correctedPlan?: ChangeSetDto | null;
}

export async function reviewPlan(
  plan: ChangeSetDto,
  shopId: string,
  prompt: string
): Promise<ReviewResult> {
  const systemPrompt = `You are an elite, independent AI Safety and Business Rule Reviewer for an e-commerce SaaS platform.
Your task is to review the proposed ChangeSet plan generated by the Planner, and verify if it is safe, correct, and complies with all business rules.

Business Rules & Safety Checks:
1. Price must be positive (greater than 0).
2. Discount must be between 0 and 100 (percentage).
3. Stock must be non-negative (0 or greater).
4. No bulk deletion of products or categories unless explicitly requested and confirmed.
5. Ensure no SQL injection, malicious code, or script tags in titles or descriptions.
6. Verify that the model names are valid ("Product", "Category").

If the plan is safe and correct, approve it.
If there are minor issues (e.g. a negative price or missing field), you can correct the plan and return the "correctedPlan".
If the plan is highly unsafe or completely incorrect, reject it.

Respond STRICTLY with a JSON object matching this schema:
{
  "approved": true | false,
  "riskLevel": "low" | "medium" | "high",
  "feedback": "Persian explanation of your review, findings, and why you approved/rejected it",
  "correctedPlan": null or a complete corrected ChangeSet object matching the Planner's schema if you made corrections
}`;

  try {
    const model = await getAiModel('simple', shopId);
    const result = await executeChatCompletion(
      {
        model,
        messages: [
          { role: 'system', content: systemPrompt },
          {
            role: 'user',
            content: `User Original Request: ${prompt}\n\nProposed ChangeSet:\n${JSON.stringify(plan, null, 2)}`,
          },
        ],
        response_format: { type: 'json_object' },
      },
      {
        shopId,
        endpoint: 'plan-reviewer',
        slot: 'simple', // Simple is enough for safety review
        billingMode: 'platform', // Safety review is system-owned and non-billable
      }
    );

    if (result instanceof Response) {
      throw new PlanningError('Received unexpected Response object instead of ChatCompletionResult.');
    }

    if (result.success) {
      const data = JSON.parse(result.text);
      return {
        approved: !!data.approved,
        riskLevel: data.riskLevel || plan.riskLevel,
        feedback: data.feedback || '',
        correctedPlan: data.correctedPlan || null,
      };
    }

    throw new PlanningError(result.error || 'Safety review failed.');
  } catch (error: unknown) {
    console.error('[reviewPlan] Safety review failed:', error);
    return {
      approved: false,
      riskLevel: plan.riskLevel,
      feedback: 'خطا در انجام بررسی امنیتی و قوانین کسب‌وکار طرح.',
    };
  }
}
