// [HARDENED] — validation, error isolation, save safety

/**
 * Repairs a potentially malformed or truncated JSON string generated by an AI model.
 * Handles:
 * - Markdown fences (```json ... ```)
 * - Truncated/cut-off JSON by auto-closing open strings, objects, and arrays.
 * - Unescaped control characters (literal newlines/tabs) inside string values.
 * - Trailing commas before closing braces/brackets.
 * - Missing values after colons.
 */
export function repairJson(raw: string): string {
  if (!raw || typeof raw !== 'string') return '';

  // 1. Strip markdown fences
  let cleaned = raw
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();

  // 2. Find the first '{' or '['
  const firstBrace = cleaned.indexOf('{');
  const firstBracket = cleaned.indexOf('[');
  let startIndex = -1;
  if (firstBrace !== -1 && firstBracket !== -1) {
    startIndex = Math.min(firstBrace, firstBracket);
  } else if (firstBrace !== -1) {
    startIndex = firstBrace;
  } else if (firstBracket !== -1) {
    startIndex = firstBracket;
  }

  if (startIndex === -1) {
    return cleaned; // No JSON structure found, return as is
  }

  let jsonPart = cleaned.substring(startIndex);

  // 3. Scan character by character to build a repaired string
  let repaired = '';
  const stack: ('{' | '[')[] = [];
  let inString = false;
  let isEscaped = false;

  for (let i = 0; i < jsonPart.length; i++) {
    const char = jsonPart[i];

    if (inString) {
      if (isEscaped) {
        repaired += char;
        isEscaped = false;
      } else if (char === '\\') {
        repaired += char;
        isEscaped = true;
      } else if (char === '"') {
        // Close string
        inString = false;
        repaired += char;
      } else if (char === '\n' || char === '\r') {
        // Escape literal newlines inside string values
        repaired += '\\n';
      } else if (char === '\t') {
        repaired += '\\t';
      } else {
        repaired += char;
      }
    } else {
      // Outside string
      if (char === '"') {
        inString = true;
        repaired += char;
      } else if (char === '{') {
        stack.push('{');
        repaired += char;
      } else if (char === '[') {
        stack.push('[');
        repaired += char;
      } else if (char === '}') {
        if (stack[stack.length - 1] === '{') {
          stack.pop();
        }
        repaired += char;
      } else if (char === ']') {
        if (stack[stack.length - 1] === '[') {
          stack.pop();
        }
        repaired += char;
      } else {
        repaired += char;
      }
    }
  }

  // 4. Handle truncation / unclosed structures
  if (inString) {
    // We are still inside a string at the end of the input! Let's close the string first.
    repaired += '"';
    inString = false;
  }

  // Clean trailing whitespace
  repaired = repaired.trim();
  
  // If it ends with a colon, append an empty string value
  if (repaired.endsWith(':')) {
    repaired += '""';
  }
  
  // Remove trailing comma before closing brackets/braces
  if (repaired.endsWith(',')) {
    repaired = repaired.slice(0, -1);
  }

  // Pop from stack and close all open structures
  while (stack.length > 0) {
    const last = stack.pop();
    if (last === '{') {
      repaired += '}';
    } else if (last === '[') {
      repaired += ']';
    }
  }

  // 5. Additional light repairs:
  // Fix trailing commas inside structures (e.g. ,} or ,])
  repaired = repaired.replace(/,\s*([}\]])/g, '$1');

  return repaired;
}

export function extractBalancedJson(text: string): string | null {
  const firstBrace = text.indexOf('{');
  const firstBracket = text.indexOf('[');
  let startIndex = -1;
  if (firstBrace !== -1 && firstBracket !== -1) {
    startIndex = Math.min(firstBrace, firstBracket);
  } else if (firstBrace !== -1) {
    startIndex = firstBrace;
  } else if (firstBracket !== -1) {
    startIndex = firstBracket;
  }

  if (startIndex === -1) return null;

  const startChar = text[startIndex];
  const endChar = startChar === '{' ? '}' : ']';
  
  let braceCount = 0;
  let inString = false;
  let isEscaped = false;

  for (let i = startIndex; i < text.length; i++) {
    const char = text[i];
    if (inString) {
      if (isEscaped) {
        isEscaped = false;
      } else if (char === '\\') {
        isEscaped = true;
      } else if (char === '"') {
        inString = false;
      }
    } else {
      if (char === '"') {
        inString = true;
      } else if (char === startChar) {
        braceCount++;
      } else if (char === endChar) {
        braceCount--;
        if (braceCount === 0) {
          return text.substring(startIndex, i + 1);
        }
      }
    }
  }

  return text.substring(startIndex);
}

export function isTruncatedJson(text: string): boolean {
  let braceCount = 0;
  let bracketCount = 0;
  let inString = false;
  let isEscaped = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (inString) {
      if (isEscaped) {
        isEscaped = false;
      } else if (char === '\\') {
        isEscaped = true;
      } else if (char === '"') {
        inString = false;
      }
    } else {
      if (char === '"') {
        inString = true;
      } else if (char === '{') {
        braceCount++;
      } else if (char === '}') {
        braceCount--;
      } else if (char === '[') {
        bracketCount++;
      } else if (char === ']') {
        bracketCount--;
      }
    }
  }

  return inString || braceCount > 0 || bracketCount > 0;
}

export function parseAiJson<T>(
  raw: string,
  requiredFields: (keyof T)[] = [],
  fallback: Partial<T> = {}
): { data: T; warnings: string[] } {
  const warnings: string[] = [];

  if (!raw || typeof raw !== 'string') {
    warnings.push('پاسخ خام خالی یا نامعتبر بود.');
    return { data: fallback as T, warnings };
  }

  let cleaned = raw.trim();

  // 1. Try plain JSON parsing first
  try {
    const parsed = JSON.parse(cleaned);
    return validateSchema(parsed, requiredFields, fallback, warnings);
  } catch {
    // Ignore and proceed to extraction
  }

  // 2. Try extracting from one markdown JSON fence
  const fenceMatch = cleaned.match(/```json\s*([\s\S]*?)\s*```/i) || cleaned.match(/```\s*([\s\S]*?)\s*```/i);
  if (fenceMatch) {
    const fenceContent = fenceMatch[1].trim();
    try {
      const parsed = JSON.parse(fenceContent);
      return validateSchema(parsed, requiredFields, fallback, warnings);
    } catch {
      cleaned = fenceContent; // Use fence content for further repair
    }
  }

  // 3. Try extracting one balanced JSON object
  const balanced = extractBalancedJson(cleaned);
  if (balanced) {
    try {
      const parsed = JSON.parse(balanced);
      return validateSchema(parsed, requiredFields, fallback, warnings);
    } catch {
      cleaned = balanced; // Use balanced substring for repair
    }
  }

  // 4. Truncation detection and at most one deterministic repair attempt
  if (isTruncatedJson(cleaned)) {
    warnings.push('پاسخ AI ناقص (truncated) تشخیص داده شد و بازسازی شد.');
  }

  // Exactly one deterministic repair attempt
  const repaired = repairJson(cleaned);
  try {
    const parsed = JSON.parse(repaired);
    return validateSchema(parsed, requiredFields, fallback, warnings);
  } catch (err) {
    warnings.push('تلاش برای بازسازی ساختار JSON ناموفق بود.');
  }

  // Final fallback
  return { data: fallback as T, warnings };
}

function validateSchema<T>(
  parsed: any,
  requiredFields: (keyof T)[] = [],
  fallback: Partial<T> = {},
  warnings: string[]
): { data: T; warnings: string[] } {
  if (!parsed || typeof parsed !== 'object') {
    return { data: fallback as T, warnings };
  }

  for (const field of requiredFields) {
    if (parsed[field] === undefined) {
      if (fallback[field] !== undefined) {
        parsed[field] = fallback[field];
        warnings.push(`فیلد "${String(field)}" در پاسخ AI وجود نداشت و با مقدار پیش‌فرض جایگزین شد.`);
      }
    }
  }

  return { data: parsed as T, warnings };
}
