// [AI-OPTIMIZED] — caching, selective context, retry added
// [HARDENED] — validation, error isolation, save safety
import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { verifyAuth } from '@/lib/auth';
import crypto from 'crypto';
import { callAiGateway } from '@/lib/ai-gateway';

export const dynamic = 'force-dynamic';

// Helper to get cached analysis or manual count from SystemSetting
async function getSetting(key: string): Promise<string | null> {
  const setting = await prisma.systemSetting.findUnique({ where: { key } });
  return setting ? setting.value : null;
}

// Helper to save setting in SystemSetting
async function saveSetting(key: string, value: string) {
  await prisma.systemSetting.upsert({
    where: { key },
    update: { value },
    create: { key, value }
  });
}

export async function GET(request: Request) {
  try {
    const decoded = await verifyAuth(request, 'admin');
    if (!decoded || !decoded.shopId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const shopId = decoded.shopId;
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type') || 'daily'; // 'daily' | 'weekly' | 'monthly'
    const forceRefresh = searchParams.get('FORCE_REFRESH') === 'true';

    // 1. Fetch Shop Settings and check age
    const shopSettings = await prisma.shopSettings.findUnique({
      where: { shopId }
    });

    if (!shopSettings) {
      return NextResponse.json({ error: 'تنظیمات فروشگاه یافت نشد.' }, { status: 404 });
    }

    const shopCreatedAt = shopSettings.createdAt || new Date();
    const shopAgeInDays = Math.ceil((new Date().getTime() - shopCreatedAt.getTime()) / (1000 * 60 * 60 * 24));

    // Check if requested tab is disabled based on shop age
    if (type === 'weekly' && shopAgeInDays < 7) {
      return NextResponse.json({
        success: false,
        disabled: true,
        reason: 'این فروشگاه کمتر از یک هفته است که ساخته شده و داده‌های کافی برای تحلیل هفتگی وجود ندارد.'
      });
    }

    if (type === 'monthly' && shopAgeInDays < 30) {
      return NextResponse.json({
        success: false,
        disabled: true,
        reason: 'این فروشگاه کمتر از یک ماه است که ساخته شده و داده‌های کافی برای تحلیل ماهانه وجود ندارد.'
      });
    }

    const now = new Date();
    const todayDateString = now.toISOString().split('T')[0];

    // Check manual limit count for today
    const limitKey = `ai_analyst_manual_count_${shopId}_${todayDateString}`;
    const manualCountStr = await getSetting(limitKey);
    const manualCount = manualCountStr ? parseInt(manualCountStr) : 0;

    // 2. Check if we are in the end-of-day random 1-hour window for automatic daily analysis
    const randomHour = (parseInt(shopId.slice(-4), 16) % 3) + 21; // 21, 22, or 23
    const currentHour = now.getHours();
    const isAutoWindow = type === 'daily' && currentHour === randomHour;

    const autoGeneratedKey = `ai_analyst_auto_generated_${shopId}_${todayDateString}`;
    const wasAutoGeneratedToday = await getSetting(autoGeneratedKey) === 'true';

    // Gather formatted data to compute dataHash
    const formattedData = await getFormattedData(shopId, type, shopSettings.shopName || 'فروشگاه من');
    const dataHash = crypto.createHash('sha256').update(JSON.stringify(formattedData)).digest('hex');

    // 3. Check if cached analysis exists in DB using the new key pattern
    const cacheKey = `ai_analyst_${shopId}_${type}_${dataHash}`;
    const cachedDataStr = await getSetting(cacheKey);

    if (cachedDataStr && !forceRefresh && (!isAutoWindow || wasAutoGeneratedToday)) {
      try {
        const parsed = JSON.parse(cachedDataStr);
        const ageInHours = (Date.now() - parsed.timestamp) / (1000 * 60 * 60);
        
        if (ageInHours < 6) {
          return NextResponse.json({
            success: true,
            analysis: parsed.analysis,
            manualCount,
            shopAgeInDays
          });
        }
      } catch (e) {
        console.warn('Failed to parse cached analyst data:', e);
      }
    }

    // Generate fresh analysis
    const freshAnalysis = await generateAnalysis(shopId, type, formattedData);
    
    // Store with timestamp
    const cacheValue = {
      timestamp: Date.now(),
      analysis: freshAnalysis
    };
    await saveSetting(cacheKey, JSON.stringify(cacheValue));

    if (isAutoWindow && !wasAutoGeneratedToday) {
      await saveSetting(autoGeneratedKey, 'true');
    }

    return NextResponse.json({
      success: true,
      analysis: freshAnalysis,
      manualCount,
      shopAgeInDays
    });

  } catch (error: any) {
    console.error('[ERROR] [AI Analyst GET]:', error);
    return NextResponse.json({ error: 'خطای سرور در پردازش درخواست.' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const decoded = await verifyAuth(request, 'admin');
    if (!decoded || !decoded.shopId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const shopId = decoded.shopId;
    const { searchParams } = new URL(request.url);
    const type = searchParams.get('type') || 'daily';
    const forceRefresh = searchParams.get('FORCE_REFRESH') === 'true';

    const now = new Date();
    const todayDateString = now.toISOString().split('T')[0];

    // Check daily manual limit
    const limitKey = `ai_analyst_manual_count_${shopId}_${todayDateString}`;
    const manualCountStr = await getSetting(limitKey);
    const manualCount = manualCountStr ? parseInt(manualCountStr) : 0;

    if (manualCount >= 2) {
      return NextResponse.json({
        error: 'شما به سقف ۲ تحلیل دستی در روز رسیده‌اید. تحلیل‌های دستی بعدی فردا فعال خواهند شد.'
      }, { status: 429 });
    }

    // Fetch Shop Settings
    const shopSettings = await prisma.shopSettings.findUnique({
      where: { shopId }
    });

    if (!shopSettings) {
      return NextResponse.json({ error: 'تنظیمات فروشگاه یافت نشد.' }, { status: 404 });
    }

    // Gather formatted data to compute dataHash
    const formattedData = await getFormattedData(shopId, type, shopSettings.shopName || 'فروشگاه من');
    const dataHash = crypto.createHash('sha256').update(JSON.stringify(formattedData)).digest('hex');

    // Check if cached analysis exists in DB using the new key pattern
    const cacheKey = `ai_analyst_${shopId}_${type}_${dataHash}`;
    const cachedDataStr = await getSetting(cacheKey);

    let freshAnalysis;
    let isCacheHit = false;

    if (cachedDataStr && !forceRefresh) {
      try {
        const parsed = JSON.parse(cachedDataStr);
        const ageInHours = (Date.now() - parsed.timestamp) / (1000 * 60 * 60);
        
        if (ageInHours < 6) {
          freshAnalysis = parsed.analysis;
          isCacheHit = true;
        }
      } catch (e) {
        console.warn('Failed to parse cached analyst data in POST:', e);
      }
    }

    if (!isCacheHit) {
      // Generate fresh analysis
      freshAnalysis = await generateAnalysis(shopId, type, formattedData);
      
      // Store with timestamp
      const cacheValue = {
        timestamp: Date.now(),
        analysis: freshAnalysis
      };
      await saveSetting(cacheKey, JSON.stringify(cacheValue));
    }

    // Increment manual count
    const newCount = manualCount + 1;
    await saveSetting(limitKey, String(newCount));

    return NextResponse.json({
      success: true,
      analysis: freshAnalysis,
      manualCount: newCount
    });

  } catch (error: any) {
    console.error('[ERROR] [AI Analyst POST]:', error);
    return NextResponse.json({ error: 'خطای سرور در پردازش درخواست.' }, { status: 500 });
  }
}

// Core function to gather data and format it
async function getFormattedData(shopId: string, type: string, shopName: string) {
  const now = new Date();
  const successfulStatuses = ['paid', 'shipped', 'delivered'];

  // Define Time Boundaries based on type
  let startDate: Date;
  let prevStartDate: Date;
  let prevEndDate: Date;
  let periodName: string;

  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);

  if (type === 'daily') {
    startDate = todayStart;
    prevStartDate = new Date(todayStart.getTime() - 24 * 60 * 60 * 1000);
    prevEndDate = todayStart;
    periodName = 'امروز';
  } else if (type === 'weekly') {
    startDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
    prevStartDate = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
    prevEndDate = startDate;
    periodName = '۷ روز گذشته';
  } else {
    startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    prevStartDate = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);
    prevEndDate = startDate;
    periodName = '۳۰ روز گذشته';
  }

  // Gather Financial Data
  const currentOrders = await prisma.order.findMany({
    where: {
      shopId,
      status: { in: successfulStatuses },
      createdAt: { gte: startDate }
    },
    select: { finalAmount: true }
  });
  const revenueCurrent = currentOrders.reduce((sum, o) => sum + o.finalAmount, 0);
  const orderCountCurrent = currentOrders.length;
  const avgBasketCurrent = orderCountCurrent > 0 ? Math.round(revenueCurrent / orderCountCurrent) : 0;

  const prevOrders = await prisma.order.findMany({
    where: {
      shopId,
      status: { in: successfulStatuses },
      createdAt: { gte: prevStartDate, lt: prevEndDate }
    },
    select: { finalAmount: true }
  });
  const revenuePrev = prevOrders.reduce((sum, o) => sum + o.finalAmount, 0);
  const orderCountPrev = prevOrders.length;
  const avgBasketPrev = orderCountPrev > 0 ? Math.round(revenuePrev / orderCountPrev) : 0;

  // Gather Product Data
  const topSellingItems = await prisma.orderItem.groupBy({
    by: ['productId'],
    where: {
      shopId,
      order: { status: { in: successfulStatuses }, createdAt: { gte: startDate } }
    },
    _sum: { quantity: true },
    orderBy: { _sum: { quantity: 'desc' } },
    take: 3
  });

  const topProducts = await Promise.all(
    topSellingItems.map(async (item) => {
      const product = await prisma.product.findFirst({
        where: { id: item.productId, shopId },
        select: { title: true, price: true, stock: true }
      });
      const qty = item._sum.quantity || 0;
      return {
        title: product?.title || 'محصول حذف شده',
        qty,
        stock: product?.stock ?? 0
      };
    })
  );

  const soldProductIdsRaw = await prisma.orderItem.findMany({
    where: {
      shopId,
      order: { status: { in: successfulStatuses }, createdAt: { gte: startDate } }
    },
    select: { productId: true },
    distinct: ['productId']
  });
  const soldProductIds = soldProductIdsRaw.map(item => item.productId);

  const unsoldProducts = await prisma.product.findMany({
    where: {
      shopId,
      isActive: true,
      id: { notIn: soldProductIds }
    },
    select: { title: true },
    orderBy: { createdAt: 'desc' },
    take: 3
  });

  const lowStockProducts = await prisma.product.findMany({
    where: {
      shopId,
      isActive: true,
      stock: { lte: 3 }
    },
    select: { title: true, stock: true },
    orderBy: { stock: 'asc' },
    take: 3
  });

  // Gather Customers Data
  const newCustomersCount = await prisma.user.count({
    where: {
      shopId,
      role: 'customer',
      createdAt: { gte: startDate }
    }
  });

  // Gather Traffic Data
  const pageViews = await prisma.pageView.findMany({
    where: {
      shopId,
      createdAt: { gte: startDate }
    },
    select: { ip: true }
  });
  const visitsCount = new Set(pageViews.map(pv => pv.ip || 'unknown')).size;
  const conversionRate = visitsCount > 0 ? parseFloat(((orderCountCurrent / visitsCount) * 100).toFixed(2)) : 0;

  const failedPaymentsCount = await prisma.order.count({
    where: {
      shopId,
      status: 'pending',
      createdAt: { gte: startDate }
    }
  });

  // Order Status
  const pendingOrdersCount = await prisma.order.count({
    where: {
      shopId,
      paymentStatus: 'paid',
      shippingStatus: { in: ['new', 'processing'] }
    }
  });

  const cancelledOrdersCount = await prisma.order.count({
    where: {
      shopId,
      status: 'cancelled',
      createdAt: { gte: startDate }
    }
  });

  const unansweredTicketsCount = await prisma.ticket.count({
    where: {
      shopId,
      status: { in: ['new', 'in_progress'] }
    }
  });

  const unansweredReviewsCount = await prisma.review.count({
    where: {
      shopId,
      status: 'pending'
    }
  });

  return {
    shopName,
    period: periodName,
    startDate: startDate.toLocaleDateString('fa-IR'),
    endDate: now.toLocaleDateString('fa-IR'),
    sales: {
      totalSales: revenueCurrent,
      prevTotalSales: revenuePrev,
      orderCount: orderCountCurrent,
      prevOrderCount: orderCountPrev,
      avgBasket: avgBasketCurrent,
      prevAvgBasket: avgBasketPrev
    },
    products: {
      topSelling: topProducts,
      unsold: unsoldProducts.map(p => p.title),
      lowStock: lowStockProducts.map(p => ({ title: p.title, stock: p.stock }))
    },
    customers: {
      newCustomers: newCustomersCount
    },
    behavioral: {
      visits: visitsCount,
      conversionRate,
      failedPayments: failedPaymentsCount
    },
    status: {
      pendingOrders: pendingOrdersCount,
      cancelledOrders: cancelledOrdersCount,
      unansweredTickets: unansweredTicketsCount,
      unansweredReviews: unansweredReviewsCount
    }
  };
}

// Core function to generate analysis using central AI Gateway
async function generateAnalysis(shopId: string, type: string, formattedData: any) {
  const SYSTEM_PROMPT = `تو یک تحلیلگر حرفه‌ای و فوق‌العاده باهوش فروشگاه اینترنتی با تخصص در هک رشد و مارکتینگ هستی.
وظیفه تو این است که داده‌های فروشگاه را دریافت کرده و فقط و فقط هشدارهای حیاتی و ترفندهای طلایی (Tricks) فوق‌العاده کوتاه، کاربردی و سریع برای افزایش فروش ارائه دهی.

قوانین سخت تحلیل:
1. از تکرار هرگونه داده آماری کلی (مثل میزان فروش، تعداد سفارش و...) که در داشبورد وجود دارد خودداری کن. کاربر این آمارها را می‌بیند.
2. توضیحات باید به شدت کوتاه، خلاصه، کپسولی و تلگرافی باشند (هر توضیح حداکثر ۱۰ الی ۱۵ کلمه). کاربر متن‌های طولانی را نمی‌خواند!
3. فقط ترفندهای عملیاتی و واقعی بنویس که فردا صبح قابل انجام باشند و مستقیماً به یک اقدام هوشمند (smartAction) متصل شوند.
4. به هیچ وجه برای smartAction مقدار type برابر با "none" نده مگر اینکه هیچ اقدام فیزیکی غیرممکن باشد. باید به جای "none"، همیشه نوع اقدام و پرامپت دقیق آن را تولید کنی تا برای تمام پیشنهادها دکمه‌ی اجرای خودکار فعال باشد.
5. پیشنهاد استراتژیک (strategicProposal) باید کاملاً دقیق، عددی و عملیاتی باشد. به هیچ عنوان از عبارات کلی مثل "بهبود تجربه کاربری"، "تمرکز بر کیفیت" یا "کاهش سبد رها شده" استفاده نکن!
   مثال بد: "تمرکز بر بهبود تجربه کاربری" یا "کاهش سبد رها شده"
   مثال خوب: "میانگین سبد ۱۲٪ افت داشته در حالی که سفارش رشد کرده -> upsell در صفحه پرداخت اضافه کن" یا "تخفیف ۲۴ ساعته آزمایشی برای محصول X جهت تشخیص مشکل قیمت یا توضیح فعال کن"
6. لینک‌های هشدارهای فوری (alerts[].action.url) باید حتماً به زبان انگلیسی باشند (مانند /admin/products یا /admin/orders) و حتماً پارامتر ?aiPrompt=... به انتهای آن‌ها اضافه شود تا هوش مصنوعی آن صفحه کاربر را راهنمایی کند (مثال: /admin/discounts?aiPrompt=...). به هیچ عنوان از کلمات فارسی در slug یا url استفاده نکن!
7. حداکثر ۲ هشدار فوری (فقط اگر واقعاً بحرانی هستند) و حداکثر ۲ ترفند طلایی مارکتینگ ارائه بده.
8. پاسخ خود را دقیقاً در قالب ساختار JSON زیر برگردان و هیچ متن اضافی قبل یا بعد از آن ننویس.

قالب خروجی JSON مورد انتظار:
{
  "alerts": [
    {
      "type": "low_stock" | "pending_orders" | "unanswered_tickets" | "failed_payments",
      "title": "عنوان هشدار (حداکثر ۵ کلمه)",
      "description": "توضیح هشدار (فقط یک جمله بسیار کوتاه، حداکثر ۱۰ کلمه. مثال: محصول X رو به اتمام است.)",
      "action": {
        "label": "عنوان دکمه اقدام",
        "url": "آدرس انگلیسی صفحه مربوطه در پنل مدیریت به همراه پارامتر aiPrompt (مثلا /admin/products?aiPrompt=چگونه...)"
      }
    }
  ],
  "suggestions": [
    {
      "title": "عنوان ترفند طلایی (حداکثر ۵ کلمه)",
      "trick": "توضیح ترفند عملیاتی در یک جمله کوتاه و فوق‌العاده کاربردی (حداکثر ۱۵ کلمه)",
      "smartAction": {
        "type": "create_discount" | "edit_product" | "create_blog" | "create_story",
        "payload": {
          "prompt": "پرامپت پیشنهادی برای دستیار هوشمند مربوطه (بسیار دقیق و آماده اعمال تغییرات)",
          "url": "آدرس صفحه دارای دستیار هوشمند (مثلاً /admin/discounts یا /admin/products یا /admin/blog)"
        }
      }
    }
  ],
  "strategicProposal": {
    "text": "یک پیشنهاد استراتژیک عددی، دقیق و بسیار کوتاه برای دوره بعدی (مثال: میانگین سبد ۱۲٪ افت داشته در حالی که سفارش رشد کرده -> upsell در صفحه پرداخت اضافه کن)",
    "smartAction": {
      "type": "create_discount" | "edit_product" | "create_blog" | "create_story",
      "payload": {
        "prompt": "پرامپت پیشنهادی برای دستیار هوشمند مربوطه جهت اجرای خودکار پیشنهاد استراتژیک",
        "url": "آدرس صفحه دارای دستیار هوشمند (مثلاً /admin/discounts یا /admin/products یا /admin/blog)"
      }
    }
  }
}`;

  const result = await callAiGateway<any>({
    shopId,
    endpoint: 'dashboard:ai-analyst',
    slot: 'complex',
    messages: [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: `داده‌های واقعی فروشگاه برای تحلیل (${type}):\n${JSON.stringify(formattedData, null, 2)}` }
    ],
    mode: 'json',
    temperature: 0.1,
    maxTokens: 1000,
    requiredFields: [],
    fallbackValue: {},
  });

  if (!result.success || !result.data) {
    throw new Error(result.error || 'تحلیل هوشمند داشبورد ناموفق بود.');
  }

  return result.data;
}
